### ISSUE TITLE
Styling of buttons

### ISSUE THREAD

**Issue by fribergr** [Ifnot/PopConfirm#18]
Hi,

First of all, thanks for a great project!

I'm wondering if there is any way to style the buttons for confirming / cancelling? Currently I think they are a bit to close to each other.

I was not able to add these styles in an easy way. 
Do you have any suggestions?

Best regards,
Robin

**Comment by Ifnot** [comment]
Hi and thanks for using my plugin :)

As i am using basic bootstrap components you can inspect elements and do a styling on it !

For example, something like this should work

```css
. popover > .popover-content > .button-group > button {
   margin: 0 5px 0 5px;
}
```
